### ISSUE TITLE
Radium-ShaderEditor crashes

### ISSUE THREAD

**Issue by hoshiryu** [STORM-IRIT/Radium-Apps#34]
The `Radium-ShaderEditor` app crashes at `GeometryComponent.inl`, line 127 because the Material does not exist
```
- 04:04:58 PM ERROR: Required material converter Ra::Engine::RawShaderMaterialData not found!
```

see issue https://github.com/STORM-IRIT/Radium-Engine/issues/694

**Comment by nmellado** [comment]
Progress on this issue will be tracked in https://github.com/STORM-IRIT/Radium-Engine/issues/694

**Comment by nmellado** [comment]
Fixed.
